name: SmallRye Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.adoc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'README.adoc'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        shell: bash
        run: |
          mvn -B verify
